version: "3"

services:
  db:
    image: postgres:12-alpine
    restart: on-failure
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: plane
      POSTGRES_DB: plane
      POSTGRES_PASSWORD: plane
    command: postgres -c 'max_connections=1000'
    networks:
      - app_network
  redis:
    image: redis:6.2.7-alpine
    restart: on-failure
    command: redis-server --maxmemory-policy allkeys-lru --maxmemory 200mb
    networks:
      - app_network
  plane_web:
    container_name: plane_web
    build:
      context: .
      dockerfile: ./apps/plane/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network

  plane_api:
    container_name: plane_api
    build:
      context: ./apiserver
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:8000
    environment:
      SENTRY_DSN: $SENTRY_DSN
      WEB_URL: $WEB_URL
      PGUSER: plane
      PGPASSWORD: plane
      PGHOST: db
      REDIS_URL: 'redis://redis:6379/'
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SECRET_KEY: $SECRET_KEY
    networks:
      - app_network
    depends_on:
      - db
      - redis
    command: ./bin/takeoff
    links:
      - db
      - redis
networks:
  app_network:
    external: true

volumes:
  postgres-data:
